# Generated by Django 4.1.2 on 2022-10-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('icon_url', models.CharField(max_length=200)),
                ('manifest_url', models.CharField(max_length=200)),
                ('disabled', models.BooleanField()),
            ],
        ),
    ]
